### ISSUE TITLE
How do I use the UI, like https://ask.databend.rs/

### ISSUE THREAD

**Issue by zopenb** [datafuselabs/askbend#51]
At present, I can get the return through curl, how do I start the webpage, and query through the webpage

**Comment by hantmac** [comment]
cc @Chasen-Zhang

**Comment by bohutang** [comment]
@he-bowen Sorry for later reply, did you resolve this issue now?

**Comment by Chasen-Zhang** [comment]
> At present, I can get the return through curl, how do I start the webpage, and query through the webpage

First, make sure you have installed Node and the Yarn/npm package manager.

If you are in local development mode, follow these steps: 

```js

cd web
yarn
yarn run dev  (or npm run dev)

```

and the The request will be forwarded to https://ask.databend.rs/
https://github.com/datafuselabs/askbend/blob/main/web/vite.config.ts#L22

Apologies for not including a clear documentation explanation; I will add it immediately.

**Comment by zopenb** [comment]
@Chasen-Zhang 
Excuse me again, currently through the command, but can't open the UI port,
`npm run dev --host x.x.x.x`
 or can only forward the request to the https://ask.databend.rs/ or can the address be customized?
![image](https://user-images.githubusercontent.com/69750910/232974737-7adbccd7-f32e-4e46-81ab-0aaf97b7e764.png)

**Comment by Chasen-Zhang** [comment]
> @Chasen-Zhang Excuse me again, currently through the command, but can't open the UI port, `npm run dev --host x.x.x.x` or can only forward the request to the https://ask.databend.rs/ or can the address be customized? ![image](https://user-images.githubusercontent.com/69750910/232974737-7adbccd7-f32e-4e46-81ab-0aaf97b7e764.png)

I understand what you mean. You can refer to this article, and I hope it will be helpful to you.  You may need to do the mapping yourself.
https://emmapopoola.medium.com/setting-up-a-custom-domain-for-your-local-apps-mac-os-linux-c68798722143

If you want to use an exposed host, you can do it like this( BTW, https://github.com/datafuselabs/askbend/pull/52, This PR will be merged soon; you can update the code, and you'll be good to go.) 
https://github.com/datafuselabs/askbend/blob/891686d617a8d94463e5159f28cf1cd11590b0bf/web/package.json#L9
